DROP DATABASE Readery

CREATE DATABASE Readery
GO

USE Readery
GO

CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY(1,1),
	Nome NVARCHAR(100) NOT NULL,
	Email NVARCHAR(150) UNIQUE NOT NULL,
	SenhaHash NVARCHAR(32) NOT NULL,
	GeneroUsuario NVARCHAR(10) NULL,
	DescricaoUsuario NVARCHAR(500) NULL,
	FotoURL NVARCHAR(500) NULL,
	DataCadastro DATETIME2(0) NOT NULL DEFAULT DATEADD(HOUR, -3, sysutcdatetime())
)
GO

CREATE TABLE Editora(
	IdEditora INT PRIMARY KEY IDENTITY(1,1),
	NomeEditora NVARCHAR(100) UNIQUE NOT NULL
)
GO

CREATE TABLE Livro(
	IdLivro INT PRIMARY KEY IDENTITY(1,1),
	Titulo NVARCHAR(150) NOT NULL,
	Sinopse NVARCHAR(MAX) NULL,
	ISBN VARCHAR(15) UNIQUE NULL,
	NumPaginas INT NULL,
	CapaURL NVARCHAR(500) NULL,
	EditoraId INT NOT NULL
	CONSTRAINT FK_Livro_Editora FOREIGN KEY(EditoraID) REFERENCES Editora(IdEditora),
	UsuarioId INT NULL,
	CONSTRAINT FK_Criado_Por_Usuario FOREIGN KEY(UsuarioId) REFERENCES Usuario(IdUsuario)
)
GO

CREATE TABLE Avaliacao(
	IdAvaliacao INT PRIMARY KEY IDENTITY(1,1),
	Nota TINYINT NOT NULL DEFAULT 0,
	DataAvaliacao DATETIME2(0) NOT NULL,
	UsuarioId INT NOT NULL,
	CONSTRAINT FK_Usuario_Avaliador FOREIGN KEY(UsuarioId) REFERENCES Usuario(IdUsuario),
	LivroId INT NOT NULL,
	CONSTRAINT FK_Livro_Avaliado FOREIGN KEY(LivroId) REFERENCES Livro(IdLivro)
)
GO

CREATE TABLE EstadoLeitura(
	IdStatus INT PRIMARY KEY IDENTITY(1,1),
	Estado NVARCHAR(20) UNIQUE NOT NULL
)
GO

CREATE TABLE Estante(
	IdEstante INT PRIMARY KEY IDENTITY,
	PaginaAtual INT NULL,
	UsuarioId INT NOT NULL,
	CONSTRAINT FK_Usuario_Estante FOREIGN KEY(UsuarioId) REFERENCES Usuario(IdUsuario),
	LivroId INT NOT NULL,
	CONSTRAINT FK_Livro_Estante FOREIGN KEY(LivroId) REFERENCES Livro(IdLivro),
	StatusId INT NOT NULL,
	CONSTRAINT FK_Status_Estante FOREIGN KEY(StatusId) REFERENCES EstadoLeitura(IdStatus)
)
GO

CREATE TABLE Genero(
	IdGenero INT PRIMARY KEY IDENTITY,
	NomeGenero VARCHAR(50) UNIQUE NOT NULL
)
GO

CREATE TABLE LivroGenero(
	LivroId INT, 
	CONSTRAINT FK_Livro_Genero FOREIGN KEY(LivroId) REFERENCES Livro(IdLivro),

	GeneroId INT,
	CONSTRAINT FK_Genero_Livro FOREIGN KEY(GeneroId) REFERENCES Genero(IdGenero),
	CONSTRAINT PK_Genero_Livro PRIMARY KEY (GeneroId, LivroId)
)
GO

CREATE TABLE Autor(
	IdAutor INT PRIMARY KEY IDENTITY,
	NomeAutor VARCHAR(100) UNIQUE NOT NULL
)
GO

CREATE TABLE LivroAutor(
	LivroId INT,
	CONSTRAINT FK_Livro_Autor FOREIGN KEY(LivroId) REFERENCES Livro(IdLivro),
	
	AutorId INT,
	CONSTRAINT FK_Autor_Livro FOREIGN KEY(AutorId) REFERENCES Autor(IdAutor),
	CONSTRAINT PK_Autor_Livro PRIMARY KEY(LivroId, AutorId)
)
GO




