// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReaderyMVC.Data;

#nullable disable

namespace ReaderyMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutorLivro", b =>
                {
                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("AutorId", "LivroId");

                    b.ToTable("AutorLivro");
                });

            modelBuilder.Entity("GeneroLivro", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("GeneroId", "LivroId");

                    b.ToTable("GeneroLivro");
                });

            modelBuilder.Entity("LivroAutor", b =>
                {
                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.HasKey("LivroId", "AutorId")
                        .HasName("PK_Autor_Livro");

                    b.HasIndex("AutorId");

                    b.ToTable("LivroAutor", (string)null);
                });

            modelBuilder.Entity("LivroGenero", b =>
                {
                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("GeneroId", "LivroId")
                        .HasName("PK_Genero_Livro");

                    b.HasIndex("LivroId");

                    b.ToTable("LivroGenero", (string)null);
                });

            modelBuilder.Entity("ReaderyMVC.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAutor")
                        .HasName("PK__Autor__DD33B0310AB4ECFF");

                    b.HasIndex(new[] { "NomeAutor" }, "UQ__Autor__B69C12C9F9BA29FD")
                        .IsUnique();

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<byte>("Nota")
                        .HasColumnType("tinyint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdAvaliacao")
                        .HasName("PK__Avaliaca__78C432D8F8062B6C");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Editora", b =>
                {
                    b.Property<int>("IdEditora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditora"));

                    b.Property<string>("NomeEditora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEditora")
                        .HasName("PK__Editora__588BC4C663F0050E");

                    b.HasIndex(new[] { "NomeEditora" }, "UQ__Editora__27B73C15CDFD4953")
                        .IsUnique();

                    b.ToTable("Editora");
                });

            modelBuilder.Entity("ReaderyMVC.Models.EstadoLeitura", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdStatus")
                        .HasName("PK__EstadoLe__B450643A98039E31");

                    b.HasIndex(new[] { "Estado" }, "UQ__EstadoLe__36DF552FDE25A8EC")
                        .IsUnique();

                    b.ToTable("EstadoLeitura");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Estante", b =>
                {
                    b.Property<int>("IdEstante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstante"));

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<int?>("PaginaAtual")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdEstante")
                        .HasName("PK__Estante__B0D80B01855E219A");

                    b.HasIndex("LivroId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Estante");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("NomeGenero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGenero")
                        .HasName("PK__Genero__0F8349880B852029");

                    b.HasIndex(new[] { "NomeGenero" }, "UQ__Genero__081698E5026A6795")
                        .IsUnique();

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<string>("CapaURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EditoraId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("NumPaginas")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdLivro")
                        .HasName("PK__Livro__3B69D85A16620631");

                    b.HasIndex("EditoraId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "ISBN" }, "UQ__Livro__447D36EAD26EA84A")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Livro");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(dateadd(hour,(-3),sysutcdatetime()))");

                    b.Property<string>("DescricaoUsuario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoURL")
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("GeneroUsuario")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97C091030A");

                    b.HasIndex(new[] { "Email" }, "UQ__Usuario__A9D105345818BCBB")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LivroAutor", b =>
                {
                    b.HasOne("ReaderyMVC.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK_Autor_Livro");

                    b.HasOne("ReaderyMVC.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Autor");
                });

            modelBuilder.Entity("LivroGenero", b =>
                {
                    b.HasOne("ReaderyMVC.Models.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .IsRequired()
                        .HasConstraintName("FK_Genero_Livro");

                    b.HasOne("ReaderyMVC.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Genero");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Avaliacao", b =>
                {
                    b.HasOne("ReaderyMVC.Models.Livro", "Livro")
                        .WithMany("Avaliacaos")
                        .HasForeignKey("LivroId")
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Avaliado");

                    b.HasOne("ReaderyMVC.Models.Usuario", "Usuario")
                        .WithMany("Avaliacaos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Avaliador");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Estante", b =>
                {
                    b.HasOne("ReaderyMVC.Models.Livro", "Livro")
                        .WithMany("Estantes")
                        .HasForeignKey("LivroId")
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Estante");

                    b.HasOne("ReaderyMVC.Models.EstadoLeitura", "Status")
                        .WithMany("Estantes")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Estante");

                    b.HasOne("ReaderyMVC.Models.Usuario", "Usuario")
                        .WithMany("Estantes")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Estante");

                    b.Navigation("Livro");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Livro", b =>
                {
                    b.HasOne("ReaderyMVC.Models.Editora", "Editora")
                        .WithMany("Livros")
                        .HasForeignKey("EditoraId")
                        .IsRequired()
                        .HasConstraintName("FK_Livro_Editora");

                    b.HasOne("ReaderyMVC.Models.Usuario", "Usuario")
                        .WithMany("Livros")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_Criado_Por_Usuario");

                    b.Navigation("Editora");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Editora", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("ReaderyMVC.Models.EstadoLeitura", b =>
                {
                    b.Navigation("Estantes");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Livro", b =>
                {
                    b.Navigation("Avaliacaos");

                    b.Navigation("Estantes");
                });

            modelBuilder.Entity("ReaderyMVC.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacaos");

                    b.Navigation("Estantes");

                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
